# Домашнє завдання №1

In [1]:
## Завдання №1: Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та 
## виведіть його значення.

import numpy as np

a = np.arange(1, 11)

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
## Завдання №2: Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та 
## виведіть його значення.

zero = np.zeros((3, 3), dtype=int)

print(zero)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
## Завдання №3: Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 
## та виведіть його значення.

n = np.random.randint(1, 11, (5, 5))

print(n)

[[ 6  1  7  5 10]
 [ 3  9 10  4  4]
 [ 9  6  4  8  4]
 [ 6  9  4  4  5]
 [ 8  4  5  8  9]]


In [7]:
## Завдання №4: Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 
## та виведіть його значення.

m = np.random.rand(4, 4)

print(m)

[[0.20820994 0.76644679 0.42430998 0.92887469]
 [0.17401939 0.66794564 0.86013725 0.42596657]
 [0.32898603 0.17320749 0.74226341 0.85423246]
 [0.42766391 0.3395923  0.85606993 0.1856554 ]]


In [14]:
## Завдання №5: Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні 
## від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

array1 = np.random.randint(1, 11, 5)
array2 = np.random.randint(1, 11, 5)

print("Перший масив:", array1)
print("Другий масив:", array2)

print("Результат додавання:", array1 + array2)
print("Результат віднімання:", array1 - array2)
print("Результат множення:", array1 * array2)

Перший масив: [10  7  8 10  1]
Другий масив: [2 6 2 4 5]
Результат додавання: [12 13 10 14  6]
Результат віднімання: [ 8  1  6  6 -4]
Результат множення: [20 42 16 40  5]


In [15]:
## Завдання №6: Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

x = np.array([1, 2, 3, 4, 5, 6, 7])
y = np.array([7, 6, 5, 4, 3, 2, 1])

print(np.dot(x, y))

84


In [16]:
## Завдання №7: Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні 
## від 1 до 10 та перемножте їх між собою.

matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 3))

print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)

print("Результат множення матриць:\n", np.dot(matrix1, matrix2))

Перша матриця:
 [[3 2]
 [7 9]]
Друга матриця:
 [[8 3 3]
 [3 9 9]]
Результат множення матриць:
 [[ 30  27  27]
 [ 83 102 102]]


In [18]:
## Завдання №8: Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 
## та знайдіть її обернену матрицю.

matrix3 = np.random.randint(1, 11, (3, 3))
matrix3_inv = np.linalg.inv(matrix3)

print("Матриця:\n", matrix3)
print("Обернена матриця:\n", matrix3_inv)

Матриця:
 [[6 1 2]
 [7 3 7]
 [9 1 3]]
Обернена матриця:
 [[ 1.42857143e-01 -7.14285714e-02  7.14285714e-02]
 [ 3.00000000e+00  9.99200722e-17 -2.00000000e+00]
 [-1.42857143e+00  2.14285714e-01  7.85714286e-01]]


In [19]:
## Завдання №9: Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 
## та транспонуйте її.

matrix4 = np.random.rand(4, 4)
matrix4_trans = matrix4.T

print("Матриця:\n", matrix4)
print("Транспонована матриця:\n", matrix4_trans)

Матриця:
 [[0.27071285 0.30305604 0.48086933 0.83210048]
 [0.17663946 0.98466098 0.59545603 0.99439235]
 [0.62985539 0.45605225 0.21362194 0.26155341]
 [0.60570605 0.93226891 0.29861081 0.96225534]]
Транспонована матриця:
 [[0.27071285 0.17663946 0.62985539 0.60570605]
 [0.30305604 0.98466098 0.45605225 0.93226891]
 [0.48086933 0.59545603 0.21362194 0.29861081]
 [0.83210048 0.99439235 0.26155341 0.96225534]]


In [22]:
## Завдання №10: Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами 
## в діапазоні від 1 до 10 та перемножте матрицю на вектор.

matrix5 = np.random.randint(1, 11, (3, 4))
c = np.random.randint(1, 11, 4)

print("Матриця:\n", matrix5)
print("Вектор:\n", c)
print("Результат:\n", np.dot(matrix5, c))

Матриця:
 [[ 2  7  5  9]
 [ 3 10  6  9]
 [ 2  8  5  3]]
Вектор:
 [2 2 1 9]
Результат:
 [104 113  52]


In [23]:
## Завдання №11: Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами 
## в діапазоні від 0 до 1 та перемножте матрицю на вектор.

matrix6 = np.random.rand(2, 3)
d = np.random.rand(3)

print("Матриця:\n", matrix6)
print("Вектор:\n", d)
print("Результат:\n", np.dot(matrix6, d))

Матриця:
 [[0.51270693 0.55617882 0.16897774]
 [0.40767231 0.51120736 0.65625784]]
Вектор:
 [0.67032535 0.82263033 0.97723477]
Результат:
 [0.96634095 1.33512575]


In [24]:
## Завдання №12: Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 
## 10 та виконайте їхнє поелементне множення.

matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))

print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)

print("Результат поелементного множення матриць:\n", matrix1 * matrix2)

Перша матриця:
 [[ 2  9]
 [10  1]]
Друга матриця:
 [[4 3]
 [4 6]]
Результат поелементного множення матриць:
 [[ 8 27]
 [40  6]]


In [25]:
## Завдання №13: Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 
## 10 та знайдіть їх добуток.

matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))

print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)

print("Результат поелементного множення матриць:\n", np.dot(matrix1, matrix2))

Перша матриця:
 [[ 4 10]
 [ 6  1]]
Друга матриця:
 [[2 8]
 [5 4]]
Результат поелементного множення матриць:
 [[58 72]
 [17 52]]


In [26]:
## Завдання №14: Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 
## та знайдіть суму елементів матриці.

matrix = np.random.randint(1, 101, (5, 5))

print("Матриця:\n", matrix)
print("Сума елементів матриці:\n", matrix.sum())

Матриця:
 [[10 86  1 30 52]
 [49 71 17 14 99]
 [56 39 87 29 16]
 [64 75 82 95 15]
 [96 46 43 63 36]]
Сума елементів матриці:
 1271


In [27]:
## Завдання №15: Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 
## 10 та знайдіть їхню різницю.

matrix1 = np.random.randint(1, 11, (4, 4))
matrix2 = np.random.randint(1, 11, (4, 4))

print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)

print("Різниця матриць:\n", matrix1 - matrix2)

Перша матриця:
 [[ 6  2  5  9]
 [ 1  3  7  8]
 [ 4  8  4  6]
 [ 2  4  2 10]]
Друга матриця:
 [[ 6  9  5  8]
 [ 4  6  8  9]
 [ 6 10  7 10]
 [ 6  4  6  8]]
Різниця матриць:
 [[ 0 -7  0  1]
 [-3 -3 -1 -1]
 [-2 -2 -3 -4]
 [-4  0 -4  2]]


In [28]:
## Завдання №16: Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 
## та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

matrix = np.random.random((3, 3))
row_sums = np.sum(matrix, axis=1, keepdims=True)

print("Матриця:\n", matrix)
print("Вектор-стовпчик, що містить суму елементів кожного рядка матриці:\n", row_sums)

Матриця:
 [[0.62312336 0.03068294 0.94846421]
 [0.46395955 0.14592586 0.26491133]
 [0.79321127 0.04165028 0.84375445]]
Вектор-стовпчик, що містить суму елементів кожного рядка матриці:
 [[1.60227051]
 [0.87479674]
 [1.67861601]]


In [30]:
## Завдання №17: Створіть матрицю розміром 3x4 з довільними цілими числами і створіть матрицю з квадратами цих 
## чисел.

matrix = np.random.randint(-100, 100, (3, 4))

print("Матриця:\n", matrix)
print("Матриця з квадратами чисел v1:\n", np.square(matrix))
print("Матриця з квадратами чисел v2:\n", matrix ** 2)
print("Матриця з квадратами чисел v3:\n", matrix * matrix)


Матриця:
 [[-71  74 -81  47]
 [-31 -71 -59   4]
 [ 83 -96  89 -38]]
Матриця з квадратами чисел v1:
 [[5041 5476 6561 2209]
 [ 961 5041 3481   16]
 [6889 9216 7921 1444]]
Матриця з квадратами чисел v2:
 [[5041 5476 6561 2209]
 [ 961 5041 3481   16]
 [6889 9216 7921 1444]]
Матриця з квадратами чисел v3:
 [[5041 5476 6561 2209]
 [ 961 5041 3481   16]
 [6889 9216 7921 1444]]


In [36]:
## Завдання №18: Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 
## та знайдіть вектор з квадратними коренями цих чисел.

m = np.random.randint(1, 51, 4)

print("Вектор:\n", m)
print("Вектор з квадратними коренями v1:\n", np.sqrt(m))
print("Вектор з квадратними коренями v2:\n", m ** 0.5)


Вектор:
 [15 26 13 31]
Вектор з квадратними коренями v1:
 [3.87298335 5.09901951 3.60555128 5.56776436]
Вектор з квадратними коренями v2:
 [3.87298335 5.09901951 3.60555128 5.56776436]
